Log error info
jet-lab/jet-v1 pull request #112
Opened 2021-09-28 17:53 UTC by GHesericsu

2021-09-28 17:56 UTC, GHesericsu commented on app/rollup.config.js
> -import json from "@rollup/plugin-json";
this was a duplicate import

2021-09-28 17:57 UTC, GHesericsu commented
refactored to just use the parsed IDL object and deleted errors.ts file

2021-09-29 23:01 UTC, Tristyn commented on app/src/scripts/jet.ts
> +  if (code >=100 && code <= 300) {
The correct range is code >=100 && code < 300

2021-09-29 23:02 UTC, Tristyn commented on app/src/scripts/jet.ts
> +  const code = Number(errCode);
I would do this Number() conversion in whatever method calls getErrNameAndMessage

2021-09-29 23:06 UTC, Tristyn requested changes

2021-09-29 23:06 UTC, Tristyn commented on app/src/scripts/jet.ts
> +let customProgramErrors: CustomProgramError[];
Not a fan of global state (In fact all the global variables here should not be here)

I suggest creating a new store that stores the idl, and you access $IDL.errors instead of this global variable

2021-09-29 23:18 UTC, GHesericsu commented on app/src/scripts/jet.ts
> +  if (code >=100 && code <= 300) {
good catch thanks

2021-09-30 04:04 UTC, closed without merging

2021-09-30 04:04 UTC, GHesericsu commented
submitted a new PR err-info-refactor