toast notifications
jet-lab/jet-v1 pull request #131
Opened 2021-09-29 21:59 UTC by loganjross

2021-09-29 22:37 UTC, Tristyn commented on app/src/App.svelte
> +  <Notifications />
Cool cool I haven't looked inside Notifications yet, nice use of components

2021-09-29 22:40 UTC, Tristyn commented on app/src/components/Notifications.svelte
> +        on:click={() => n.success ? navigate("/transactions") : null}>
Would personally prefer to use `if(n.success) { navigate("/transactions") }` instead of using ternarys because you are not returning anything from the ternary here

2021-09-29 22:43 UTC, Tristyn commented on app/src/models/JetTypes.ts
> +  success: boolean,
Could replace success: boolean with a more versatile enum.
When I have a boolean I instinctively ask if there are more than just 2 states, and would it make sense to use an enum
```
enum NotificationStatus{
  Info = "Info",
  Warning = "Warning",
  Error = "Error",
}
```

2021-09-29 22:44 UTC, Tristyn commented on app/src/scripts/languages/Jet_UI_EN.json
> +      "noTrades": "You have no logged transactions with Jet."
A better name may be noTradeHistory

2021-09-29 22:45 UTC, Tristyn commented on app/src/scripts/utils.ts
> +  }, 4000);
Could you extract this 4000ms duration into a CAPS_CASE const at the top of the file?

2021-09-29 22:46 UTC, Tristyn commented on app/src/store.ts
> +export const NOTIFICATIONS = writable<Notification[]> ([]);
I like that you're initializing this store with a default value so you never have to check for null

2021-09-29 22:47 UTC, Tristyn commented on app/src/views/Cockpit.svelte
> -
🙌 🙌 🙌

2021-09-29 22:53 UTC, Tristyn requested changes

2021-09-29 22:53 UTC, Tristyn commented on app/src/views/Cockpit.svelte
> +          .replaceAll('{{TRADE ACTION}}', $TRADE_ACTION)
You will need to store $TRADE_ACTION, $CURRENT_RESERVE in a local variable because it could change by the time this code executes. Then the sendingTrade flag can be deleted

2021-09-29 22:53 UTC, Tristyn commented on app/src/views/TransactionLogs.svelte
> +          {#if $TRANSACTION_LOGS.length}
Great job on the Flight Logs, you developed that by yourself, and gave it some amazing Jet branding. Such a great feature you got out the door

2021-09-30 13:11 UTC, loganjross commented on app/src/models/JetTypes.ts
> +  success: boolean,
for now will only be 2 states but will definitely use this in other cases

2021-09-30 13:15 UTC, loganjross commented on app/src/views/Cockpit.svelte
> +          .replaceAll('{{TRADE ACTION}}', $TRADE_ACTION)
nice catch, will do

2021-09-30 13:17 UTC, loganjross commented on app/src/views/TransactionLogs.svelte
> +          {#if $TRANSACTION_LOGS.length}
thanks bruv

2021-09-30 13:44 UTC, merged